#! /usr/bin/python

import os
import time
import traceback
import subprocess
import sys

os.chdir(os.path.dirname(sys.argv[0]))
clogs = os.path.join(os.getcwd(), 'logs')
ckeep = os.path.join(os.getcwd(), 'control', 'dokeep')
cmake = os.path.join(os.getcwd(), 'control', 'domake')
cup = os.path.join(os.getcwd(), 'control', 'doupdate')
cmon = os.path.join(os.getcwd(), 'control', 'active')
cnotes = os.path.join(os.getcwd(), '..', 'notes')

def mkl(n):
	return os.path.join(clogs, n)

def mkt():
	return time.strftime('%Y%m%d%H%M%S', time.gmtime())

try:
  open(cmon, 'w').close()
  while True:
	time.sleep(5)
	ts = mkt()
	try:
		print "waking up at ", ts
		doupdate = False
		domake = False
		doall = False
		dokeep = False
		if os.path.exists(ckeep):
			dokeep = True
		if os.path.exists(cup):
			doupdate = True
			os.remove(cup)
		if os.path.exists(cmake):
			domake = True
			f = None
			r = None	
			try: 
				f = open(cmake)
				r = f.read()
				if r.strip().lower() == 'all': doall = True
			finally:
				f.close()
			r = None
			os.remove(cmake)

		if doupdate:
			n1 = mkl('%s.update.running' % ts)
			ul = open(n1, 'w', 0)
			code = subprocess.call(["svn","update"], stdout=ul, stderr=ul, cwd=cnotes)
			if code == 0:
				ul.close()			
				if 'Updated to revision' in file(n1).read():
					domake = True
				if not dokeep: os.remove(n1)
				else: os.rename(n1, mkl('%s.update' % ts))
			else:
				print >>ul, "Command terminated with exit code: ", code
				ul.close()
				os.rename(n1, mkl('%s.update.bad' % ts))
		if domake:
			n2 = mkl('%s.build.running' % ts)
			ul = open(n2, 'w', 0)
			code = subprocess.call(["./rebuild.sh", str(doall)], stdout=ul, stderr=ul, cwd=cnotes)
			if code == 0:
				ul.close()
				os.rename(n2, mkl('%s.build' % ts))
			else:
				print >>ul, "Command terminated with exit code: ", code
				ul.close()
				os.rename(n2, mkl('%s.build.bad' % ts))
	

	except:
		f = open(mkl('monitor'), 'a')
		print >>f, "--- %s ---" % ts
		traceback.print_exc(file = f)
		f.close()
finally:
	os.remove(cmon)

